#!/bin/sh -efu

. etcgit-sh-functions

write_error() {
        echo "$@" >&2
}

if [ $# -eq 0 ]; then
        if [ -n "$(_list_modified)" ]; then
                echo "$(get_branch_remote_url) $(get_branch_name)*"
                exit 1
        else
                echo "$(get_branch_remote_url) $(get_branch_name)"
                exit 0
        fi
else
        CMD="$1"; shift
        case "$CMD" in
                head)
                        (
                                hd="$(get_branch_head)"
                                echo "$hd $(get_head_message "$hd")"
                        )
                        ;;
                diff)
                        if [ $# -gt 0 ]; then
                                get_diff "$1"
                        else
                                get_diff
                        fi
			;;
		branch)
                        if [ $# -gt 0 ]; then
                                list_remote_branches "$1"
                        else
                                get_branch_name
                        fi
                        ;;
                log)
                        [ -n "${1-}" ] && in_branch="$1"
                        list_commits
                        ;;
                services)
                        list_start_seq
                        ;;
                status)
                        _list_modified
                        ;;
        esac
fi
